AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Authentication API Stack - v0.01
Parameters:
  UpdateTrigger:
    Type: String
    Default: "0"
  JwtSecretParameter:
    Type: String
    Default: "your-secret-key"  # Replace with secure value or use AWS Secrets Manager

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    Architectures:
      - x86_64
    Environment:
      Variables:
        DYNAMO_TABLE: !Ref DynamoTable
        DOMAIN: !Ref AWS::StackName
        COGNITO_USER_POOL_ID: !Ref CognitoUserPool
        COGNITO_CLIENT_ID: !Ref CognitoAppClient
        JWT_SECRET: !Ref JwtSecretParameter

Resources:
  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AuthUsers
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: AuthUserPool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: custom:biometricStatus
          AttributeDataType: String
          Mutable: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
          RequireLowercase: true

  CognitoAppClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: auth-app-client
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      PreventUserExistenceErrors: ENABLED

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      CodeUri: dashboard-app/backend/
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:UpdateItem
              Resource: !GetAtt DynamoTable.Arn
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:AdminUpdateUserAttributes
                - cognito-idp:SignUp
                - cognito-idp:ConfirmSignUp
                - cognito-idp:InitiateAuth
                - cognito-idp:RespondToAuthChallenge
              Resource: !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPool}'
    Metadata:
      UpdateTrigger: !Ref UpdateTrigger

Outputs:
  ApiEndpoint:
    Description: Default execute-api endpoint
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
  CognitoUserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPool
  CognitoAppClientId:
    Description: Cognito App Client ID
    Value: !Ref CognitoAppClient