AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Authentication API Stack - v0.01

Parameters:
  UpdateTrigger:
    Type: String
    Default: '0'
  JwtSecretParameter:
    Type: String
    Default: your-secret-key

Resources:
  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AuthUsers
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: AuthUserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      UsernameAttributes:
        - email

  CognitoAppClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: AuthAppClient
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dashboard-app/backend/build/
      Handler: main.handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Environment:
        Variables:
          DYNAMO_TABLE: AuthUsers
          DOMAIN: !Ref AWS::Region
          COGNITO_USER_POOL_ID: !Ref CognitoUserPool
          COGNITO_CLIENT_ID: !Ref CognitoAppClient
          JWT_SECRET: !Ref JwtSecretParameter
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: '2.0'
        info:
          title: !Ref AWS::StackName
        paths:
          /{proxy+}:
            x-amazon-apigateway-any-method:
              responses: {}