AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  auth-project
  SAM Template for auth backend with Secrets Manager

Globals:
  Function:
    Timeout: 20
    MemorySize: 128

Parameters:
  Environment:
    Type: String
    Default: local
    AllowedValues:
      - local
      - prod
    Description: Environment type (local or prod)

Resources:
  UserCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: UserCredentials
      Description: Stores user credentials for the auth backend
      SecretString: !If
        - IsLocal
        - '{"test@example.com": {"password": "$2b$12$KIXp8e8f9z2b3c4d5e6f7u", "requires_change": true, "totp_secret": "", "biometric_key": ""}}'
        - !Ref AWS::NoValue
      Tags:
        - Key: Environment
          Value: !Ref Environment

  AuthFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: main.handler
      Runtime: python3.12
      CodeUri: ./dashboard-app/backend
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:UpdateSecret
              Resource: !GetAtt UserCredentialsSecret.Arn
      Environment:
        Variables:
          IS_LOCAL: !If [IsLocal, true, false]
          AWS_ENDPOINT_URL: !If
            - IsLocal
            - !Sub "http://host.docker.internal:4566"
            - !Ref AWS::NoValue
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref ServerlessRestApi
      StageName: !If
        - IsLocal
        - !Ref AWS::NoValue
        - Prod
    DependsOn: AuthFunction

Conditions:
  IsLocal: !Equals [!Ref Environment, local]

Outputs:
  AuthApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  UserCredentialsSecretArn:
    Description: "ARN of the UserCredentials secret"
    Value: !GetAtt UserCredentialsSecret.Arn